package org.example.entity;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OrderColumn;
import jakarta.persistence.Table;

@Entity
@Table(name = "coming_soon")
public class ComingSoon {

    // ============================================================
    // ID
    // ============================================================

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ============================================================
    // PRODUCT INFORMATION
    // ============================================================

    @Column(nullable = false, length = 255)
    private String productName;

    @Column(nullable = false, length = 150)
    private String brand;

    @Column(length = 2000)
    private String description;

    // ============================================================
    // DISPLAY DATE RANGE
    // ============================================================

    /*
     * Product starts appearing in the Coming Soon section
     * from this date.
     */
    @Column(nullable = false)
    private LocalDate displayFromDate;

    /*
     * Product remains visible through this date.
     *
     * Example:
     * displayFromDate = 2026-10-01
     * displayToDate   = 2026-10-15
     *
     * The product is visible from Oct 1 through Oct 15.
     * On Oct 16 it automatically disappears from the
     * user-facing Coming Soon banner.
     */
    @Column(nullable = false)
    private LocalDate displayToDate;

    // ============================================================
    // PRIORITY
    // ============================================================

    /*
     * Higher priority products can be displayed first.
     *
     * Example:
     * 1 = Normal
     * 2 = Medium
     * 3 = High
     * 4 = Very High
     * 5 = Top
     */
    @Column(nullable = false)
    private Integer priority = 1;

    // ============================================================
    // STATUS
    // ============================================================

    /*
     * Admin can manually disable a Coming Soon product.
     *
     * Date expiration is handled separately.
     */
    @Column(nullable = false)
    private boolean active = true;

    // ============================================================
    // IMAGES
    // ============================================================

    /*
     * Image URLs are stored separately from the main table.
     *
     * Table generated by Hibernate:
     *
     * coming_soon_images
     *
     * Columns:
     * coming_soon_id
     * image_url
     * image_order
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(
        name = "coming_soon_images",
        joinColumns = @JoinColumn(name = "coming_soon_id")
    )
    @OrderColumn(name = "image_order")
    @Column(name = "image_url", length = 1000)
    private List<String> imageUrls = new ArrayList<>();

    // ============================================================
    // GETTERS
    // ============================================================

    public Long getId() {
        return id;
    }

    public String getProductName() {
        return productName;
    }

    public String getBrand() {
        return brand;
    }

    public String getDescription() {
        return description;
    }

    public LocalDate getDisplayFromDate() {
        return displayFromDate;
    }

    public LocalDate getDisplayToDate() {
        return displayToDate;
    }

    public Integer getPriority() {
        return priority;
    }

    public boolean isActive() {
        return active;
    }

    public List<String> getImageUrls() {
        return imageUrls;
    }

    // ============================================================
    // SETTERS
    // ============================================================

    public void setId(Long id) {
        this.id = id;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setDisplayFromDate(LocalDate displayFromDate) {
        this.displayFromDate = displayFromDate;
    }

    public void setDisplayToDate(LocalDate displayToDate) {
        this.displayToDate = displayToDate;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public void setImageUrls(List<String> imageUrls) {
        this.imageUrls = imageUrls;
    }
}